name: Tracker
description: Suggest a new or update a existing public torrent tracker
projects:
  - if-you-want-peace-prepare-for-war/trackIt
labels:
  - 'Public Tracker'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for giving you time and interest, to keep this project a relevant source, for the community.
        Make sure you have read our [Contribution guidelines](/CONTRIBUTING.md)

  - type: input
    id: uri
    attributes:
      label: Full URI string to tracker
      description: full address as `protocol[://]URI[:]port/path`
      placeholder: |
        http://hpdl360g8-1.matrix.lan:6969/announce
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: Comment for change
      description: Please write why you wont this change to the open tracker list
      placeholder: |
        1. This is a public tracker
        2. This tracker is on a privacy & worksafe network
        3. I've found a privacy rule for this tracker.

    validations:
      required: true

  - type: textarea
    id: network
    attributes:
      label: Network data (Ip/Network)
      description: The network proof. Please post entire drill/dig ANSWER SECTION
      placeholder: |
        drill tracker.ipv6tracker.org @9.9.9.9
        ;; ANSWER SECTION:
        tracker.ipv6tracker.org.        60      IN      A       34.89.51.235
        tracker.ipv6tracker.org.        60      IN      A       34.94.76.146
        tracker.ipv6tracker.org.        60      IN      A       35.227.59.57
      render: bash
    validations:
      required: true

  - type: textarea
    id: whois
    attributes:
      label: whois
      description: Whois data on network from above
      placeholder: |
        whois -H 34.94.76.146
        NetRange:       34.64.0.0 - 34.127.255.255
        CIDR:           34.64.0.0/10
        NetName:        GOOGL-2
        NetHandle:      NET-34-64-0-0-1
        Parent:         NET34 (NET-34-0-0-0-0)
        NetType:        Direct Allocation
        OriginAS:
        Organization:   Google LLC (GOOGL-2)
        RegDate:        2018-09-28
        Updated:        2018-09-28
        Ref:            https://rdap.arin.net/registry/ip/34.64.0.0

        ...

      render: bash
    validations:
      required: true

  - type: dropdown
    id: software
    attributes:
      label: Software
      description: Software used for tested this tracker
      multiple: true
      options:
        - BiglyBT
        - Bitcomet
        - BitLord
        - Bitport
        - BitTorent
        - bt-torrent
        - Deluge
        - Frostwire
        - Halite
        - KTorrent
        - popcorn Time
        - qBittorent
        - qBittorent Enhanced Edition
        - Tixati
        - Torch Browser
        - Transmission (qt-Transmission, Transmission-bt)
        - uTorrent
        - Vuze
        - WebTorrent
        - Other (Please right which in comment section above)


  - type: checkboxes
    attributes:
      label: 'I do confirm that:'
      description: |
        'By not being compliant with the following, you accept you can be banned from this project'
      options:
        - label: There are no other related issues regarding this domain
          required: true
        - label: This committed tracker have been online and active for at least one month
          required: true
        - label: This commit is on a safe network
          required: true
        - label: I have read and understood the rules for [contributing](https://github.com/if-you-want-peace-prepare-for-war/trackIt/blob/master/CONTRIBUTING.md) new trackers and updating existing open tracker.
          required: true
